// apps/app-next/pages/login.tsx
import React from 'react';

import './login.module.scss';

/* eslint-disable-next-line */
export interface LoginProps {}

export function Login(props: LoginProps) {
  return (
    <div className="auth-page">
      <div className="container page">
        <div className="row">
          <div className="col-md-6 offset-md-3 col-xs-12">
            <h1 className="text-xs-center">Sign in</h1>

            <ul className="error-messages">
              <li>Login has failed</li>
            </ul>

            <form>
              <fieldset className="form-group">
                <input
                  className="form-control form-control-lg"
                  type="text"
                  placeholder="Email"
                ></input>
              </fieldset>
              <fieldset className="form-group">
                <input
                  className="form-control form-control-lg"
                  type="password"
                  placeholder="Password"
                ></input>
              </fieldset>
              <button className="btn btn-lg btn-primary pull-xs-right">
                Sign in
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Login;

// apps/app-angular-elf/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { UserDataService } from '../../shared/user-data/user-data.service';

@Component({
  selector: 'rw-login',
  templateUrl: './login.component.html',
})
export class LoginComponent {
  form = new FormGroup({
    email: new FormControl('', {
      nonNullable: true,
      validators: [Validators.required, Validators.email],
    }),
    password: new FormControl('', {
      nonNullable: true,
      validators: [Validators.required],
    }),
  });

  constructor(
    private router: Router,
    private userDataService: UserDataService
  ) {}

  onSignIn() {
    if (this.form.invalid) {
      return;
    }

    this.userDataService
      .login(this.form.controls.email.value, this.form.controls.password.value)
      .subscribe(() => this.router.navigate(['/']));
  }
}

<div class="auth-page">
  <div class="container page">
    <div class="row">
      <div class="col-md-6 offset-md-3 col-xs-12">
        <h1 class="text-xs-center">Sign in</h1>
        <p class="text-xs-center">
          <a [routerLink]="['/register']">Need an account?</a>
        </p>

        <!-- <ul class="error-messages">
          <li>That email is already taken</li>
        </ul> -->

        <form [formGroup]="form">
          <fieldset class="form-group">
            <input
              class="form-control form-control-lg"
              type="text"
              formControlName="email"
              placeholder="Email"
            />
          </fieldset>
          <fieldset class="form-group">
            <input
              class="form-control form-control-lg"
              type="password"
              formControlName="password"
              placeholder="Password"
            />
          </fieldset>
          <button
            class="btn btn-lg btn-primary pull-xs-right"
            (click)="onSignIn()"
          >
            Sign in
          </button>
        </form>
      </div>
    </div>
  </div>
</div>
